#!/bin/sh
set -e

. /usr/share/debconf/confmodule

case "$1" in
    configure)
        db_get sx1302-hal/region
        REGION="${RET:-EU868}"

        SRC="/usr/share/sx1302-hal/configs/global_conf.json.$REGION"
        DST="/etc/sx1302-hal/global_conf.json"

        install -d /etc/sx1302-hal

        # Overwrite only if:
        #  - target doesn't exist yet (fresh install), OR
        #  - we're being invoked by dpkg-reconfigure (reconfigure case)
        if [ ! -f "$DST" ] || [ -n "$DPKG_RECONFIGURE" ]; then
            if [ -f "$SRC" ]; then
                install -m 0644 "$SRC" "$DST"
            else
                echo "sx1302-hal: missing template $SRC" >&2
            fi
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'sx1302-hal-gpio-perms.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'sx1302-hal-gpio-perms.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'sx1302-hal-gpio-perms.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'sx1302-hal-gpio-perms.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'sx1302-hal-pkt-fwd.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'sx1302-hal-pkt-fwd.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'sx1302-hal-pkt-fwd.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'sx1302-hal-pkt-fwd.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'sx1302-hal-gpio-perms.service' 'sx1302-hal-pkt-fwd.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
